### PR TITLE
fix ipsw download ipa

### LINKED ISSUE #594: Download ipa: `An unknown error has occurred`
### What happened?

Executing a ipa download command returns the error ` no items found in download response`. Running it with verbose output shows that the apple server returns:

```
   • POST Download: (200):
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<plist version="1.0">
<dict>
<key>pings</key>
<array></array>
<key>failureType</key><string>5002</string>
<key>customerMessage</key><string>An unknown error has occurred</string>
<key>m-allowed</key><false/>
</dict>
</plist>
``` 

The issue seem related to: https://github.com/majd/ipatool/issues/311

### How can we reproduce this?

 `ipsw download ipa "com.google.chrome.ios" --output ./  -y --verbose`

### ipsw version

```bash
Version: 3.1.557, BuildCommit: e04666135c472c01b0a952c75195ab7b6af2b2d4
```

### Search

- [X] I did search for other open and closed issues before opening this

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by t0rr3sp3dr0**
Fixes #594

### CODE REVIEW

**Comment by blacktop** [comment]
I'm still getting:

• POST Login: (404):

and

   • POST Download: (200):
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<plist version="1.0">
<dict>
<key>pings</key>
<array></array>
<key>failureType</key><string>5002</string>
<key>customerMessage</key><string>An unknown error has occurred</string>
<key>m-allowed</key><false/>
</dict>
</plist>

going to delete my keychain entry and try again

**Comment by AltayAkkus** [comment]
Same here with empty keychain

**Comment by t0rr3sp3dr0** [comment]
I haven’t tested with an empty keychain. I’ll do that and update the PR.

**Comment by blacktop** [comment]
> I haven’t tested with an empty keychain. I’ll do that and update the PR.

Did you do a `ipsw dl dev` first? That would probably get you some good two factor auth'd session cookies

**Comment by AltayAkkus** [comment]
> Did you do a `ipsw dl dev` first? That would probably get you some good two factor auth'd session cookies

Done it, error 412 on the endpoint, still does not. Gonna give u full logs in the morning.

**Comment by blacktop** [comment]
> > Did you do a `ipsw dl dev` first? That would probably get you some good two factor auth'd session cookies
> 
> Done it, error 412 on the endpoint, still does not. Gonna give u full logs in the morning.

412 is promising, probably just needs 2fa

**Comment by AltayAkkus** [comment]
I did the 2FA tho, allowed, then entered the code. I'll try to get it wrong
tomorrow, maybe its just send inappropriately.

I intercepted my iOS App Store, it sends a request to a p70* itunes
Endpoint, which cannot be send, where do u guys read the requests from?
Also iOS or Mac?

blacktop ***@***.***> schrieb am Di., 26. Nov. 2024, 20:42:

**Comment by t0rr3sp3dr0** [comment]
I'm not really sure what is going on. I'm unable to reproduce the issue. I've deleted the Keychain item and I get 2FA prompt and pop-up as expected.

https://github.com/user-attachments/assets/025339da-4f0c-40b7-a7df-1247367dd4e3

**Comment by blacktop** [comment]
What is your macOS and iOS version?

**Comment by t0rr3sp3dr0** [comment]
Okay, I think I got it. I was able to reproduce the problem with another Apple ID.

**Comment by AltayAkkus** [comment]
```
altay@mydevice ipsw % ./ipsw dl dev
? Please type your verification code: ******
   ⨯ failed to login: failed to verify code: response received 412
```

[More verbose output](https://gist.github.com/AltayAkkus/2d9bfd1bdae6678cece6f1398efe4a6f)

**Comment by t0rr3sp3dr0** [comment]
@AltayAkkus @blacktop, could you try again? The problem that I've identified is that different Apple IDs use different iTunes Pods, and if you don't use the right one authentication fails.

**Comment by AltayAkkus** [comment]
I still have the same exact error as before, although when I use the cmd in #594 
`ipsw download ipa "com.google.chrome.ios" --output ./  -y --verbose` I merely get a storefront error (it tries to download from US store, apparently?), which is a good sign I think.

**Comment by t0rr3sp3dr0** [comment]
@AltayAkkus, could you try setting `--store-front` to your country code?

**Comment by t0rr3sp3dr0** [comment]
If that doesn't work, can you share the error?

**Comment by AltayAkkus** [comment]
https://gist.github.com/AltayAkkus/4e285730bc1a56ef2caa2e2624641941

**Comment by AltayAkkus** [comment]
Fun fact: The download for already purchased apps works again :)

**Comment by t0rr3sp3dr0** [comment]
Thanks! I was able to reproduce the problem using a non-American Apple ID. I'll modify the code to extract the store front from the Apple ID by default.

**Comment by t0rr3sp3dr0** [comment]
https://mitmproxy.org + OS X Mavericks VM 😂

image

**Comment by blacktop** [comment]
I think this solution is going to work for a lot of people, it however still has issues for me.

for example I am not getting prompted for a 2fa for my guid (as we discussed) there must be a way to reset it? I think I saw a 'logout' URL in the bag?

when I changed my guid to "0" to get prompted it failed in the old way again.

I'll test more tomorrow.

**Comment by blacktop** [comment]
lol i just tried again and just put a random code in of 123456 and it worked and is now working and downloading correctly 😆

**Comment by t0rr3sp3dr0** [comment]
The thing is I've just hit a road block on the purchase side of things. I was only able to performing a purchase while using the Mac App Store user-agent, but to sign in without the whole body signature thing I need to sign-in using the Apple Configurator user-agent.

This is what happens when you try to make a purchase as the Configurator:

```xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<plist version="1.0">
<dict>
<key>pings</key>
<array></array>
<key>metrics</key>
<dict>
  <key>dialogId</key><string>MZCommerce.SystemError</string>
  <key>message</key><string>Unable to process your re</string>
  <key>options</key>
  <array>
    <string>OK</string>
  </array>
  <key>actionUrl</key><string>buy.itunes.apple.com/WebObjects/MZBuy.woa/wa/buyProduct?PRH=54&amp;Pod=54</string>
  <key>asnState</key><integer>0</integer>
  <key>mtTopic</key><string>xp_its_main</string>
  <key>eventType</key><string>dialog</string>
</dict>
<key>failureType</key><string></string>
<key>customerMessage</key><string>Unable to process your request.</string>
<key>m-allowed</key><false/>
<key>dialog</key>
<dict><key>m-allowed</key><false/>
<key>isFree</key><true/>
<key>message</key><string>Unable to process your request.</string>
<key>explanation</key><string>Try again later.</string>
<key>defaultButton</key><string>ok</string>
<key>okButtonString</key><string>OK</string>
<key>initialCheckboxValue</key><true/></dict>
<key>cancel-purchase-batch</key><true/>
</dict>
</plist>
```

And this is what happens if I try to sign-in as the Apple Configurator and reuse the session as the Mac App Store:

```xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<plist version="1.0">
<dict>
<key>pings</key>
<array></array>
<key>metrics</key>
<dict>
  <key>dialogId</key><string>MZCommerce.BadPasswordToken</string>
  <key>message</key><string>Your password has changed</string>
  <key>messageCode</key><string>2002</string>
  <key>options</key>
  <array>
    <string>OK</string>
  </array>
  <key>actionUrl</key><string>buy.itunes.apple.com/WebObjects/MZBuy.woa/wa/buyProduct?PRH=54&amp;Pod=54</string>
  <key>asnState</key><integer>0</integer>
  <key>mtTopic</key><string>xp_its_main</string>
  <key>eventType</key><string>dialog</string>
</dict>
<key>failureType</key><string>2002</string>
<key>customerMessage</key><string>Your password has changed.</string>
<key>m-allowed</key><false/>
<key>dialog</key>
<dict><key>m-allowed</key><false/>
<key>isFree</key><true/>
<key>message</key><string>Your password has changed.</string>
<key>explanation</key><string>Please sign out from the Account menu and sign in again.</string>
<key>defaultButton</key><string>ok</string>
<key>okButtonString</key><string>OK</string>
<key>initialCheckboxValue</key><true/></dict>
<key>cancel-purchase-batch</key><true/>
</dict>
</plist>
```

And I've checked the last, and the cause seems simple. The `passwordToken` issues when signing in as the MAS is a hexadecimal value and signing in as the Configurator gives me a completely different token in base64.

**Comment by t0rr3sp3dr0** [comment]
And this is what I expect to get on a successful purchase. I got it by signing in as the MAS and making the `buyProduct` request to get an iOS app.

```xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<plist version="1.0">
<dict>
<key>pings</key>
<array></array>
<key>jingleDocType</key><string>purchaseSuccess</string>
<key>jingleAction</key><string>purchaseProduct</string>
<key>status</key><integer>0</integer>

<key>authorized</key><false/><key>download-queue-item-count</key><integer>0</integer>
<key>songList</key>
<array>
</array>
<key>metrics</key>
<dict>

  <key>pliIds</key>
  <array>
    <string>94072936604715</string>
  </array>
  <key>sapTypes</key>
  <array>
    <string>3</string>
  </array>
  <key>sapLineItemTypes</key>
  <array>
    <string>0</string>
  </array>
  <key>itemIds</key>
  <array>
    <integer>6446901002</integer>
  </array>
  <key>price</key><real>0.00</real>
  <key>priceType</key><string>STDRDL</string>
  <key>productTypes</key>
  <array>
    <string>C</string>
  </array>
  <key>mtTopic</key><string>xp_its_main</string>
  <key>currency</key><string>USD</string>
  <key>extractedCommerceEvent_latestLineItem_sapType</key><string>3</string>
  <key>commerceEvent_purchase_priceType</key><string>STDRDL</string>
  <key>commerceEvent_storeFrontId</key><string>143441</string>
  <key>extractedCommerceEvent_latestLineItem_adamId</key><string>6446901002</string>
  <key>extractedCommerceEvent_latestLineItem_currencyCodeISO3A</key><string>USD</string>
  <key>commerceEvent_result_resultType</key><integer>0</integer>
  <key>extractedCommerceEvent_latestLineItem_amountPaid</key><real>0.00000</real>
  <key>commerceEvent_flowType</key><integer>17</integer>
  <key>commerceEvent_flowStep</key><integer>27</integer>
  <key>commerceEvent_correlationKey</key><string>AZP7YO2UE7P45QAR4ZFIB5MWPI</string>
</dict>
<key>subscriptionStatus</key>
<dict>
<key>terms</key>
<array>
<dict>
<key>type</key><string>Store</string>
<key>latestTerms</key><integer>32</integer>
<key>agreedToTerms</key><integer>39</integer>
<key>source</key><string>account</string>
</dict>
</array>
<key>account</key>
<dict>
<key>isMinor</key><false/>
<key>suspectUnderage</key><false/>
</dict>
<key>family</key>
<dict>
<key>hasFamily</key><true/>
<key>hasFamilyGreaterThanOneMember</key><true/>
<key>isHoH</key><true/>
</dict>
</dict>
</dict>
</plist>
```

**Comment by t0rr3sp3dr0** [comment]
> for example I am not getting prompted for a 2fa for my guid (as we discussed) there must be a way to reset it? I think I saw a 'logout' URL in the bag?

In my testing, signing out does not invalidate the 2FA authentication and you will not be prompted for it again when using the same GUID. There must be a way to invalidate the sessions, but I have no clue.

> when I changed my guid to "0" to get prompted it failed in the old way again.

The GUID must be a valid MAC Address, otherwise the server rejects it.

**Comment by AltayAkkus** [comment]
> This was my best attempt so far to fix purchases: [t0rr3sp3dr0/ipsw@fix-download...t0rr3sp3dr0:ipsw:fix-purchase](https://github.com/t0rr3sp3dr0/ipsw/compare/fix-download...t0rr3sp3dr0:ipsw:fix-purchase).

Still got the "Your account is not valid for use in the U.S. store. You must switch to the German store before purchasing." error :/

**Comment by dschm1dt** [comment]
The download of already purchased items work for me with the fix. Tested it with accounts from different countries. 

Thanks for investigating the issue. I previously tried intercepting the store traffic from a jailbroken iPhone without success. The macos way is very interesting.

**Comment by t0rr3sp3dr0** [comment]
> Still got the "Your account is not valid for use in the U.S. store. You must switch to the German store before purchasing." error :/

I haven’t fixed the storefront issue in my attempt to fix purchases. It should be a straightforward fix, you just need to get that information from the sign-in response and pass it as a header in the purchase request. But before that, I want to reduce the number of variables and try to make purchases work with an American Apple ID.

**Comment by t0rr3sp3dr0** [comment]
@blacktop, please let me know if are still facing some problem with this implementation. If not, I think we can merge it and try to fix purchases in another PR.

**Comment by blacktop** [comment]
just tested w/ both my devices/accounts and LGTM 👍

**Comment by Oisann** [comment]
> > OS X Mavericks VM
> 
> LMAO okay my Sonoma 14.5 has far too many security features which stop me from intercepting the App Store traffic :D Amazing to see that they support OS X even though its like 11 yrs old.

I couldn't even get it to work on Sonoma. Couldn't see AppStore data at all, but safari (and some other apps) worked fine. Was pulling my hair all day 😬 

Anyway, thanks a lot everyone. Saved my sanity.

**Comment by z-tux-mind** [comment]
> whole body signature

@t0rr3sp3dr0 do you have any documentation/example usage of this `whole body signature thing` needed to sign-in as MacAppStore instead of Configurator?

I can work on implementing it, at first on MacOS, then reverse how it works to make it work on other platforms too.
Apart from the purchase procedure you already implemented in [fix-purchase](https://github.com/t0rr3sp3dr0/ipsw/compare/fix-download...t0rr3sp3dr0:ipsw:fix-purchase), have you successfully used the MAS user-agent to download IPAs?

If we can get the MAS login, purchase and download, this would completely fix the IPA download feature, at least on MacOS.

Thanks for your help and precious time!

**Comment by tux-mind** [comment]
@t0rr3sp3dr0 do you have any documentation or example usage of the `whole body signature thing` you mentioned?

In addition to fix the purchase on you [fix-purchase](https://github.com/t0rr3sp3dr0/ipsw/compare/fix-download...t0rr3sp3dr0:ipsw:fix-purchase) branch, were you able to use the MAS user-agent to download IPAs?

If I can use the MAS user-agent to login, purchase and download, we would have fixed the IPA download feature.
However, I suspect that the login part is the trickiest, as it smells like I would have to add a trusted MacOS device to the account, probably involving some confirmation dialog on another trusted device.

Thank you for your help and precious time!

**Pull request merged**
