### PR TITLE
Update download.md: fix typo Teh -> The

### PR DESCRIPTION
**Pull request by muescha**
fix typo: Teh -> The

### CODE REVIEW

**Comment by blacktop** [comment]
thank you! however, i believe this is now fixed

**Comment by muescha** [comment]
as i check the `master` branch: it is not fixed

see:
- https://github.com/muescha/ipsw/blob/gh-pages/docs/guides/download/index.html
- https://github.com/muescha/ipsw/blob/master/www/docs/guides/download.md

**Comment by blacktop** [comment]
are you checking the master branch of your own fork?

**Comment by muescha** [comment]
you got me - yes you are right. sorry

**Comment by blacktop** [comment]
no worries 😄

**Pull request closed without merging**
