### PR TITLE
`ipsw download` with no args should print usage

### PR DESCRIPTION
**Pull request by KritantaDev**
(in my dumb opinion) I figured `ipsw download` with no args should print usage, in line with behaviour across the rest of the project.

I haven't been able to get the build environment for this project working, but I doubt the single-line change should cause any issues.

### CODE REVIEW

**Comment by blacktop** [comment]
WRT the build env have you tried `make setup` and `make dry_release` ?

**Comment by KritantaDev** [comment]
Made the initial fork back in June/July so that particular problem may have been fixed by now

Just noticed github workflow actions have been added recently as well, looks like those are passing on my repo:

https://github.com/KritantaDev/ipsw/actions/runs/1137139465

**Comment by blacktop** [comment]
LGTM, thank you! 👍

**Comment by blacktop** [comment]
Had to revert 😞 it broke the default download cmd and we GOTZ ta get those sweet sweet iOS15 iPhone14,x IPSWs downloaded yo!

**Pull request merged**
