### PR TITLE
fix: types with protocol qualified are not built-ins

### PR DESCRIPTION
**Pull request by t0rr3sp3dr0**
I made a mistake in #443 and the code detects things like `id <OS_dispatch_queue>` as built-ins. While `id` is a built-in, `OS_dispatch_queue` is not.

This patch addresses the problem by looking for built-ins only when we have an unqualified type. When we have a qualified type, we split the type in two and check both parts separately: https://github.com/blacktop/ipsw/blob/7c77867d955b4047a30141b6140bcaaba0726d21/internal/commands/macho/objc.go#L1014-L1017

### CODE REVIEW

**Comment by blacktop** [comment]
Not sure this is a good test, because it's Foundation, but: *(check out)*
- Foundation/NSAKDeserializerStream.h
- Foundation/NSKeyedUnarchiver.h
- Foundation/NSOperation.h
- Foundation/NSOperationQueue.h
- Foundation/NSXPCConnection.h
- Foundation/NSXPCListener.h

Might be time to start using regep vs. strings.Contains

**Comment by t0rr3sp3dr0** [comment]
Okay, we have two problems:
1. We have a mix of Objective-C encoded types like `@"NSObject<OS_dispatch_group>"` and regular types like `NSString *`. Trying to parse both at the same time is not pretty straightforward.
2. There is no exhaustive grammar for Objective-C type encoding besides the compiler implementation itself. I couldn't find a place that documents `A` or `%`, for example. The only thing we can 100% rely on is [14 thousand lines of C++](https://github.com/llvm/llvm-project/blob/main/clang/lib/AST/ASTContext.cpp).

**Comment by t0rr3sp3dr0** [comment]
I believe to have addressed the problems you listed.

But, unrelated to this PR, I found that we are not representing some more obscure types properly.

- ipsw Header:
```objc
@interface NSDecimalNumber : NSNumber {
    /* instance variables */
    unsigned int x :8 _exponent;
    unsigned int x :4 _length;
    unsigned int x :1 _isNegative;
    unsigned int x :1 _isCompact;
    unsigned int x :1 _reserved;
    unsigned int x :1 _hasExternalRefCount;
    unsigned int x :16 _refs;
    unsigned short * _mantissa;
}
```

- Official Apple SDK Header:
```objc
@interface NSDecimalNumber : NSNumber {
@private
    signed   int _exponent:8;
    unsigned int _length:4;
    unsigned int _isNegative:1;
    unsigned int _isCompact:1;
    unsigned int _reserved:1;
    unsigned int _hasExternalRefCount:1;
    unsigned int _refs:16;
    unsigned short _mantissa[];
}
```

**Comment by t0rr3sp3dr0** [comment]
Another example.

ipsw:
```objc
@interface _NSObserverList : NSObject {
    /* instance variables */
    id _owner;
    id _observers;
    atomic unsigned int _observerCount;
    struct os_unfair_lock_s { unsigned int _os_unfair_lock_opaque; } _observersLock;
}
```

Expected:
```objc
@interface _NSObserverList : NSObject {
    /* instance variables */
    id _owner;
    id _observers;
    _Atomic unsigned int _observerCount;
    struct os_unfair_lock_s { unsigned int _os_unfair_lock_opaque; } _observersLock;
}
```

**Comment by blacktop** [comment]
> Another example.
> 
> ipsw:
> 
> ```objc
> @interface _NSObserverList : NSObject {
>     /* instance variables */
>     id _owner;
>     id _observers;
>     atomic unsigned int _observerCount;
>     struct os_unfair_lock_s { unsigned int _os_unfair_lock_opaque; } _observersLock;
> }
> ```
> 
> Expected:
> 
> ```objc
> @interface _NSObserverList : NSObject {
>     /* instance variables */
>     id _owner;
>     id _observers;
>     _Atomic unsigned int _observerCount;
>     struct os_unfair_lock_s { unsigned int _os_unfair_lock_opaque; } _observersLock;
> }
> ```

Is `atomic` not a valid alias for `_Atomic` ?

**Comment by blacktop** [comment]
> I believe to have addressed the problems you listed.
> 
> But, unrelated to this PR, I found that we are not representing some more obscure types properly.
> 
> * ipsw Header:
> 
> ```objc
> @interface NSDecimalNumber : NSNumber {
>     /* instance variables */
>     unsigned int x :8 _exponent;
>     unsigned int x :4 _length;
>     unsigned int x :1 _isNegative;
>     unsigned int x :1 _isCompact;
>     unsigned int x :1 _reserved;
>     unsigned int x :1 _hasExternalRefCount;
>     unsigned int x :16 _refs;
>     unsigned short * _mantissa;
> }
> ```
> 
>  * Official Apple SDK Header:
> 
> ```objc
> @interface NSDecimalNumber : NSNumber {
> @private
>     signed   int _exponent:8;
>     unsigned int _length:4;
>     unsigned int _isNegative:1;
>     unsigned int _isCompact:1;
>     unsigned int _reserved:1;
>     unsigned int _hasExternalRefCount:1;
>     unsigned int _refs:16;
>     unsigned short _mantissa[];
> }
> ```

I believed this is fixed in `go-macho`

**Comment by blacktop** [comment]
> Another example.
> 
> ipsw:
> 
> ```objc
> @interface _NSObserverList : NSObject {
>     /* instance variables */
>     id _owner;
>     id _observers;
>     atomic unsigned int _observerCount;
>     struct os_unfair_lock_s { unsigned int _os_unfair_lock_opaque; } _observersLock;
> }
> ```
> 
> Expected:
> 
> ```objc
> @interface _NSObserverList : NSObject {
>     /* instance variables */
>     id _owner;
>     id _observers;
>     _Atomic unsigned int _observerCount;
>     struct os_unfair_lock_s { unsigned int _os_unfair_lock_opaque; } _observersLock;
> }
> ```

replaced `atomic` w/ `_Atomic` in go-macho

**Comment by t0rr3sp3dr0** [comment]
`_Atomic` and `atomic` are actually different. The former is a C type qualifier and it is used with C types, while the latter is a Objective-C property attribute and cannot be used outside property definitions.

**Comment by t0rr3sp3dr0** [comment]
Just resolved the conflicts, PTAL

**Comment by blacktop** [comment]
> Just resolved the conflicts, PTAL

Can you also rebase from `master` to pull in the go-macho fixes?  I'm still seeing a lot of weird things in those Foundation headers

**Comment by blacktop** [comment]
`Foundation/NSConcreteFileHandle.h`

`@class out unsigned long long;`

**Comment by blacktop** [comment]
`Foundation/NSOperationQueue.h`

`@class __backingQueue"@"NSObject;`

**Comment by blacktop** [comment]
I forgot to ask about this but in `Foundation/NSProgressRegistrar-Protocol.h`  this PR removes: `@protocol OS_dispatch_queue;`

Maybe it doesn't make sense to have `forward declarations` of protocols in protocol headers?

**Comment by blacktop** [comment]
`Foundation/NSXPCConnection.h`

`@class remote"@"OS_xpc_remote_connection");`

**Comment by t0rr3sp3dr0** [comment]
I’ll try to address these problems this weekend.

**Comment by t0rr3sp3dr0** [comment]
I'll have to fix some stuff in go-macho to make this work properly. I'll send the PR shortly.

**Comment by blacktop** [comment]
> I'll have to fix some stuff in go-macho to make this work properly. I'll send the PR shortly.

merged your go-macho PR and cut a release 👍

**Comment by t0rr3sp3dr0** [comment]
Okay, just tested against Foundation and the only thing weird I found was `@class by copy id;` in `NSSpellServer` and `@class undefined;` in multiple places. But that's because of go-macho as well.

I'm reviewing [these maps](https://github.com/blacktop/go-macho/blob/ea4593cb2cc47605ef7c8af539347ee7ac13b00a/types/objc/type_encoding.go#L11-L64) and will submit a PR there. Beyond spaces in `bycopy`, `byref`, and `oneway`, there are other problems like `int128` instead of `__int128` and `BOOL` instead of `_Bool`. But I'm having a hard time validating these types:

```go
	"z": "size_t",
	"Z": "int32",
	"w": "wchar_t",
	"!":  "vector",
	"Vv": "void",
```

I don't know if `zZw!V` are legacy types but, with Xcode 15.3, I get `unsupported type encoding spec` when using them with `[[NSMethodSignature signatureWithObjCTypes:s] debugDescription]`. Do you know anything about them or have an example where they are used?

**Comment by blacktop** [comment]
> Okay, just tested against Foundation and the only thing weird I found was `@class by copy id;` in `NSSpellServer` and `@class undefined;` in multiple places. But that's because of go-macho as well.
> 
> I'm reviewing [these maps](https://github.com/blacktop/go-macho/blob/ea4593cb2cc47605ef7c8af539347ee7ac13b00a/types/objc/type_encoding.go#L11-L64) and will submit a PR there. Beyond spaces in `bycopy`, `byref`, and `oneway`, there are other problems like `int128` instead of `__int128` and `BOOL` instead of `_Bool`. But I'm having a hard time validating these types:
> 
> ```go
> 	"z": "size_t",
> 	"Z": "int32",
> 	"w": "wchar_t",
> 	"%": "NXAtom",
> 	"!":  "vector",
> 	"Vv": "void",
> ```
> 
> I don't know if `zZw%!V` are legacy types but, with Xcode 15.3, I get `unsupported type encoding spec` when using them with `[[NSMethodSignature signatureWithObjCTypes:s] debugDescription]`. Do you know anything about them or have an example where they are used?

I can't remember where I saw some of those originally, they were added 3-4yrs ago.

Do you know how 'gnu register' should be represented?

**Comment by blacktop** [comment]
https://github.com/apple-oss-distributions/objc4/blob/196363c165b175ed925ef6b9b99f558717923c47/runtime/runtime.h

! and % are real though

**Comment by t0rr3sp3dr0** [comment]
Take a look at https://github.com/blacktop/go-macho/pull/52. I've removed `Vv` from there (because it should be `oneway void`) and left the other types untouched.

**Comment by blacktop** [comment]
I pushed some fixes including some that you mentioned to go-macho and the output is looking pretty good to me now 👍

**Comment by t0rr3sp3dr0** [comment]
About `%`, this is interesting: https://github.com/gcc-mirror/gcc/blob/11c13111ac64a035d6c4ea6c118eff4ece7a9d9b/libobjc/objc/runtime.h#L116-L118.

Apparently, GCC also has `|`: https://github.com/gcc-mirror/gcc/blob/11c13111ac64a035d6c4ea6c118eff4ece7a9d9b/libobjc/objc/runtime.h#L129C1-L129C27.

I would love to have some code that actually uses these things.

**Comment by t0rr3sp3dr0** [comment]
Let me rebase my PR in go-macho, there are some changes worth picking there.

**Comment by blacktop** [comment]
> Let me rebase my PR in go-macho, there are some changes worth picking there.

agreed

**Comment by blacktop** [comment]
> About `%`, this is interesting: https://github.com/gcc-mirror/gcc/blob/11c13111ac64a035d6c4ea6c118eff4ece7a9d9b/libobjc/objc/runtime.h#L116-L118.
> 
> Apparently, GCC also has `|`: https://github.com/gcc-mirror/gcc/blob/11c13111ac64a035d6c4ea6c118eff4ece7a9d9b/libobjc/objc/runtime.h#L129C1-L129C27.
> 
> I would love to have some code that actually uses these things.

nice find!

**Comment by blacktop** [comment]
Tested a few of my fav dylibs and it looks good 👍

**Pull request merged**
